export const FETCHING_SMRUF_START = "FETCHING_SMRF_START";
export const FETCHING_SMRF_SUCCESS = "FETCHING_SMRF_SUCCESS";
export const FETCHING_SMRF_FAILURE = "FETCHING_SMRF_FAILURE";


export const ADDING_SMURF_START = "ADDING_SMURF_START";
export const ADDING_SMURF_SUCCESS = "ADDING_SMURF_SUCCESS";
export const ADDING_SMURF_FAILURE = "ADDING_SMURF_FAILURE";


export const DELETING_SMURF_START = "DELETING_SMURF_START";
export const DELETING_SMURF_SUCCESS = "DELETING_SMURF_SUCCESS";
export const DELETING_SMURF_FAILURE = "FETCHING_SMRUF_FAILURE";